// Generated by scripts/gen-types.mjs from the migrations — do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      amenities: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          capacity: number | null;
          max_duration_minutes: number;
          min_duration_minutes: number;
          weekly_limit_per_unit: number;
          booking_window_days: number;
          min_notice_minutes: number;
          open_time: string;
          close_time: string;
          buffer_minutes: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          capacity?: number | null;
          max_duration_minutes?: number;
          min_duration_minutes?: number;
          weekly_limit_per_unit?: number;
          booking_window_days?: number;
          min_notice_minutes?: number;
          open_time?: string;
          close_time?: string;
          buffer_minutes?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          capacity?: number | null;
          max_duration_minutes?: number;
          min_duration_minutes?: number;
          weekly_limit_per_unit?: number;
          booking_window_days?: number;
          min_notice_minutes?: number;
          open_time?: string;
          close_time?: string;
          buffer_minutes?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      amenity_blackouts: {
        Row: {
          id: string;
          amenity_id: string;
          period: string;
          reason: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          amenity_id: string;
          period: string;
          reason?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          amenity_id?: string;
          period?: string;
          reason?: string | null;
          created_by?: string | null;
        };
        Relationships: [];
      };
      announcement_reads: {
        Row: {
          announcement_id: string;
          user_id: string;
          read_at: string;
        };
        Insert: {
          announcement_id: string;
          user_id: string;
          read_at?: string;
        };
        Update: {
          announcement_id?: string;
          user_id?: string;
          read_at?: string;
        };
        Relationships: [];
      };
      announcements: {
        Row: {
          id: string;
          title: string;
          body: string;
          category: Database["public"]["Enums"]["announcement_category"];
          audience: Database["public"]["Enums"]["announcement_audience"];
          target_floors: number[];
          target_units: string[];
          urgent: boolean;
          publish_at: string;
          expires_at: string | null;
          source: Database["public"]["Enums"]["content_source"];
          source_ref: Json | null;
          push_sent_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          body: string;
          category?: Database["public"]["Enums"]["announcement_category"];
          audience?: Database["public"]["Enums"]["announcement_audience"];
          target_floors?: number[];
          target_units?: string[];
          urgent?: boolean;
          publish_at?: string;
          expires_at?: string | null;
          source?: Database["public"]["Enums"]["content_source"];
          source_ref?: Json | null;
          push_sent_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          body?: string;
          category?: Database["public"]["Enums"]["announcement_category"];
          audience?: Database["public"]["Enums"]["announcement_audience"];
          target_floors?: number[];
          target_units?: string[];
          urgent?: boolean;
          publish_at?: string;
          expires_at?: string | null;
          source?: Database["public"]["Enums"]["content_source"];
          source_ref?: Json | null;
          push_sent_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      automation_rules: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          trigger: Json;
          conditions: Json;
          actions: Json;
          enabled: boolean;
          priority: number;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          trigger: Json;
          conditions?: Json;
          actions: Json;
          enabled?: boolean;
          priority?: number;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          trigger?: Json;
          conditions?: Json;
          actions?: Json;
          enabled?: boolean;
          priority?: number;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      bookings: {
        Row: {
          id: string;
          amenity_id: string;
          tenant_id: string;
          unit: string;
          period: string;
          status: Database["public"]["Enums"]["booking_status"];
          guests: number;
          note: string | null;
          energy_kwh: number | null;
          reminder_sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          amenity_id: string;
          tenant_id: string;
          unit: string;
          period: string;
          status?: Database["public"]["Enums"]["booking_status"];
          guests?: number;
          note?: string | null;
          energy_kwh?: number | null;
          reminder_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          amenity_id?: string;
          tenant_id?: string;
          unit?: string;
          period?: string;
          status?: Database["public"]["Enums"]["booking_status"];
          guests?: number;
          note?: string | null;
          energy_kwh?: number | null;
          reminder_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      control_commands: {
        Row: {
          id: number;
          device_id: string;
          room_id: string | null;
          command: Json;
          source: Database["public"]["Enums"]["command_source"];
          user_id: string | null;
          rule_id: string | null;
          reason: string | null;
          status: Database["public"]["Enums"]["command_status"];
          error: string | null;
          created_at: string;
          sent_at: string | null;
          acked_at: string | null;
        };
        Insert: {
          device_id: string;
          room_id?: string | null;
          command: Json;
          source: Database["public"]["Enums"]["command_source"];
          user_id?: string | null;
          rule_id?: string | null;
          reason?: string | null;
          status?: Database["public"]["Enums"]["command_status"];
          error?: string | null;
          created_at?: string;
          sent_at?: string | null;
          acked_at?: string | null;
        };
        Update: {
          device_id?: string;
          room_id?: string | null;
          command?: Json;
          source?: Database["public"]["Enums"]["command_source"];
          user_id?: string | null;
          rule_id?: string | null;
          reason?: string | null;
          status?: Database["public"]["Enums"]["command_status"];
          error?: string | null;
          created_at?: string;
          sent_at?: string | null;
          acked_at?: string | null;
        };
        Relationships: [];
      };
      device_events: {
        Row: {
          id: number;
          device_id: string;
          type: Database["public"]["Enums"]["device_event_type"];
          payload: Json;
          occurred_at: string;
          ticket_id: string | null;
          announcement_id: string | null;
          acknowledged_by: string | null;
          acknowledged_at: string | null;
        };
        Insert: {
          device_id: string;
          type: Database["public"]["Enums"]["device_event_type"];
          payload?: Json;
          occurred_at?: string;
          ticket_id?: string | null;
          announcement_id?: string | null;
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
        };
        Update: {
          device_id?: string;
          type?: Database["public"]["Enums"]["device_event_type"];
          payload?: Json;
          occurred_at?: string;
          ticket_id?: string | null;
          announcement_id?: string | null;
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
        };
        Relationships: [];
      };
      devices: {
        Row: {
          id: string;
          hardware_id: string;
          name: string;
          type: Database["public"]["Enums"]["device_type"];
          location: string;
          circuit: string | null;
          room_id: string | null;
          status: Database["public"]["Enums"]["device_status"];
          firmware_version: string | null;
          battery_pct: number | null;
          rssi_dbm: number | null;
          last_seen: string | null;
          calibration: Json;
          config: Json;
          simulated: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          hardware_id: string;
          name: string;
          type: Database["public"]["Enums"]["device_type"];
          location: string;
          circuit?: string | null;
          room_id?: string | null;
          status?: Database["public"]["Enums"]["device_status"];
          firmware_version?: string | null;
          battery_pct?: number | null;
          rssi_dbm?: number | null;
          last_seen?: string | null;
          calibration?: Json;
          config?: Json;
          simulated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          hardware_id?: string;
          name?: string;
          type?: Database["public"]["Enums"]["device_type"];
          location?: string;
          circuit?: string | null;
          room_id?: string | null;
          status?: Database["public"]["Enums"]["device_status"];
          firmware_version?: string | null;
          battery_pct?: number | null;
          rssi_dbm?: number | null;
          last_seen?: string | null;
          calibration?: Json;
          config?: Json;
          simulated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      energy_sources: {
        Row: {
          id: string;
          name: string;
          kind: Database["public"]["Enums"]["energy_source_kind"];
          device_id: string | null;
          max_import_kw: number | null;
          max_export_kw: number | null;
          capacity_kwh: number | null;
          peak_limit_kw: number | null;
          enabled: boolean;
        };
        Insert: {
          id?: string;
          name: string;
          kind: Database["public"]["Enums"]["energy_source_kind"];
          device_id?: string | null;
          max_import_kw?: number | null;
          max_export_kw?: number | null;
          capacity_kwh?: number | null;
          peak_limit_kw?: number | null;
          enabled?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          kind?: Database["public"]["Enums"]["energy_source_kind"];
          device_id?: string | null;
          max_import_kw?: number | null;
          max_export_kw?: number | null;
          capacity_kwh?: number | null;
          peak_limit_kw?: number | null;
          enabled?: boolean;
        };
        Relationships: [];
      };
      ev_chargers: {
        Row: {
          id: string;
          label: string;
          device_id: string | null;
          ocpp_id: string | null;
          max_kw: number;
          fleet_only: boolean;
          status: Database["public"]["Enums"]["device_status"];
          created_at: string;
        };
        Insert: {
          id?: string;
          label: string;
          device_id?: string | null;
          ocpp_id?: string | null;
          max_kw?: number;
          fleet_only?: boolean;
          status?: Database["public"]["Enums"]["device_status"];
          created_at?: string;
        };
        Update: {
          id?: string;
          label?: string;
          device_id?: string | null;
          ocpp_id?: string | null;
          max_kw?: number;
          fleet_only?: boolean;
          status?: Database["public"]["Enums"]["device_status"];
          created_at?: string;
        };
        Relationships: [];
      };
      ev_sessions: {
        Row: {
          id: string;
          tenant_id: string | null;
          charger_id: string | null;
          vehicle_label: string | null;
          requested_kwh: number;
          departure_time: string;
          status: Database["public"]["Enums"]["ev_session_status"];
          delivered_kwh: number;
          plan: Json | null;
          est_complete_at: string | null;
          started_at: string | null;
          ended_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          charger_id?: string | null;
          vehicle_label?: string | null;
          requested_kwh: number;
          departure_time: string;
          status?: Database["public"]["Enums"]["ev_session_status"];
          delivered_kwh?: number;
          plan?: Json | null;
          est_complete_at?: string | null;
          started_at?: string | null;
          ended_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          charger_id?: string | null;
          vehicle_label?: string | null;
          requested_kwh?: number;
          departure_time?: string;
          status?: Database["public"]["Enums"]["ev_session_status"];
          delivered_kwh?: number;
          plan?: Json | null;
          est_complete_at?: string | null;
          started_at?: string | null;
          ended_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      forecasts: {
        Row: {
          id: number;
          timestamp: string;
          predicted_kw: number;
          lower_kw: number | null;
          upper_kw: number | null;
          actual_kw: number | null;
          model: string;
          generated_at: string;
        };
        Insert: {
          timestamp: string;
          predicted_kw: number;
          lower_kw?: number | null;
          upper_kw?: number | null;
          actual_kw?: number | null;
          model: string;
          generated_at?: string;
        };
        Update: {
          timestamp?: string;
          predicted_kw?: number;
          lower_kw?: number | null;
          upper_kw?: number | null;
          actual_kw?: number | null;
          model?: string;
          generated_at?: string;
        };
        Relationships: [];
      };
      laundry_machines: {
        Row: {
          id: string;
          label: string;
          kind: Database["public"]["Enums"]["machine_kind"];
          device_id: string | null;
          channel: number | null;
          state: Database["public"]["Enums"]["machine_state"];
          state_since: string;
          est_done_at: string | null;
          signature: Json;
        };
        Insert: {
          id?: string;
          label: string;
          kind: Database["public"]["Enums"]["machine_kind"];
          device_id?: string | null;
          channel?: number | null;
          state?: Database["public"]["Enums"]["machine_state"];
          state_since?: string;
          est_done_at?: string | null;
          signature?: Json;
        };
        Update: {
          id?: string;
          label?: string;
          kind?: Database["public"]["Enums"]["machine_kind"];
          device_id?: string | null;
          channel?: number | null;
          state?: Database["public"]["Enums"]["machine_state"];
          state_since?: string;
          est_done_at?: string | null;
          signature?: Json;
        };
        Relationships: [];
      };
      laundry_watchers: {
        Row: {
          user_id: string;
          kind: Database["public"]["Enums"]["machine_kind"];
          created_at: string;
        };
        Insert: {
          user_id: string;
          kind: Database["public"]["Enums"]["machine_kind"];
          created_at?: string;
        };
        Update: {
          user_id?: string;
          kind?: Database["public"]["Enums"]["machine_kind"];
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: number;
          user_id: string;
          kind: Database["public"]["Enums"]["notification_kind"];
          title: string;
          body: string;
          url: string | null;
          urgent: boolean;
          send_push: boolean;
          send_email: boolean;
          ref: Json;
          created_at: string;
          read_at: string | null;
          push_sent_at: string | null;
          email_sent_at: string | null;
        };
        Insert: {
          user_id: string;
          kind: Database["public"]["Enums"]["notification_kind"];
          title: string;
          body?: string;
          url?: string | null;
          urgent?: boolean;
          send_push?: boolean;
          send_email?: boolean;
          ref?: Json;
          created_at?: string;
          read_at?: string | null;
          push_sent_at?: string | null;
          email_sent_at?: string | null;
        };
        Update: {
          user_id?: string;
          kind?: Database["public"]["Enums"]["notification_kind"];
          title?: string;
          body?: string;
          url?: string | null;
          urgent?: boolean;
          send_push?: boolean;
          send_email?: boolean;
          ref?: Json;
          created_at?: string;
          read_at?: string | null;
          push_sent_at?: string | null;
          email_sent_at?: string | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: Database["public"]["Enums"]["app_role"];
          status: Database["public"]["Enums"]["account_status"];
          unit: string | null;
          room_letter: string | null;
          floor: number | null;
          phone: string | null;
          shuttle_alerts: boolean;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: Database["public"]["Enums"]["app_role"];
          status?: Database["public"]["Enums"]["account_status"];
          unit?: string | null;
          room_letter?: string | null;
          floor?: number | null;
          phone?: string | null;
          shuttle_alerts?: boolean;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: Database["public"]["Enums"]["app_role"];
          status?: Database["public"]["Enums"]["account_status"];
          unit?: string | null;
          room_letter?: string | null;
          floor?: number | null;
          phone?: string | null;
          shuttle_alerts?: boolean;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent: string | null;
          created_at: string;
          last_used_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent?: string | null;
          created_at?: string;
          last_used_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          endpoint?: string;
          p256dh?: string;
          auth?: string;
          user_agent?: string | null;
          created_at?: string;
          last_used_at?: string | null;
        };
        Relationships: [];
      };
      rooms: {
        Row: {
          id: string;
          slug: string;
          name: string;
          amenity_id: string | null;
          device_ids: string[];
          hvac_setpoints: Json;
          override_mode: Database["public"]["Enums"]["override_mode"];
          override_until: string | null;
          override_by: string | null;
          state: Json;
          baseline_kw: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          amenity_id?: string | null;
          device_ids?: string[];
          hvac_setpoints?: Json;
          override_mode?: Database["public"]["Enums"]["override_mode"];
          override_until?: string | null;
          override_by?: string | null;
          state?: Json;
          baseline_kw?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          amenity_id?: string | null;
          device_ids?: string[];
          hvac_setpoints?: Json;
          override_mode?: Database["public"]["Enums"]["override_mode"];
          override_until?: string | null;
          override_by?: string | null;
          state?: Json;
          baseline_kw?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      routes: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          color: string;
          path: Json | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          color?: string;
          path?: Json | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          color?: string;
          path?: Json | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      runs: {
        Row: {
          id: string;
          route_id: string;
          scheduled_run_id: string | null;
          service_date: string;
          scheduled_departure: string;
          status: Database["public"]["Enums"]["run_status"];
          driver_id: string | null;
          delay_minutes: number | null;
          cancel_reason: string | null;
          started_at: string | null;
          ended_at: string | null;
          late_flagged_at: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          route_id: string;
          scheduled_run_id?: string | null;
          service_date: string;
          scheduled_departure: string;
          status?: Database["public"]["Enums"]["run_status"];
          driver_id?: string | null;
          delay_minutes?: number | null;
          cancel_reason?: string | null;
          started_at?: string | null;
          ended_at?: string | null;
          late_flagged_at?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          route_id?: string;
          scheduled_run_id?: string | null;
          service_date?: string;
          scheduled_departure?: string;
          status?: Database["public"]["Enums"]["run_status"];
          driver_id?: string | null;
          delay_minutes?: number | null;
          cancel_reason?: string | null;
          started_at?: string | null;
          ended_at?: string | null;
          late_flagged_at?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      schedule_exceptions: {
        Row: {
          id: string;
          service_date: string;
          kind: Database["public"]["Enums"]["schedule_exception_kind"];
          route_id: string | null;
          scheduled_run_id: string | null;
          departure_time: string | null;
          note: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          service_date: string;
          kind: Database["public"]["Enums"]["schedule_exception_kind"];
          route_id?: string | null;
          scheduled_run_id?: string | null;
          departure_time?: string | null;
          note?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          service_date?: string;
          kind?: Database["public"]["Enums"]["schedule_exception_kind"];
          route_id?: string | null;
          scheduled_run_id?: string | null;
          departure_time?: string | null;
          note?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      scheduled_runs: {
        Row: {
          id: string;
          route_id: string;
          day_of_week: number;
          departure_time: string;
          active: boolean;
        };
        Insert: {
          id?: string;
          route_id: string;
          day_of_week: number;
          departure_time: string;
          active?: boolean;
        };
        Update: {
          id?: string;
          route_id?: string;
          day_of_week?: number;
          departure_time?: string;
          active?: boolean;
        };
        Relationships: [];
      };
      shuttle_locations: {
        Row: {
          id: number;
          run_id: string;
          lat: number;
          lng: number;
          heading: number | null;
          speed_mps: number | null;
          accuracy_m: number | null;
          recorded_at: string;
        };
        Insert: {
          run_id: string;
          lat: number;
          lng: number;
          heading?: number | null;
          speed_mps?: number | null;
          accuracy_m?: number | null;
          recorded_at?: string;
        };
        Update: {
          run_id?: string;
          lat?: number;
          lng?: number;
          heading?: number | null;
          speed_mps?: number | null;
          accuracy_m?: number | null;
          recorded_at?: string;
        };
        Relationships: [];
      };
      shuttle_run_metrics: {
        Row: {
          run_id: string;
          distance_km: number;
          duration: string;
          idle_time: string;
          stop_count: number;
          est_energy_kwh: number | null;
          created_at: string;
        };
        Insert: {
          run_id: string;
          distance_km: number;
          duration: string;
          idle_time: string;
          stop_count: number;
          est_energy_kwh?: number | null;
          created_at?: string;
        };
        Update: {
          run_id?: string;
          distance_km?: number;
          duration?: string;
          idle_time?: string;
          stop_count?: number;
          est_energy_kwh?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      stops: {
        Row: {
          id: string;
          route_id: string;
          name: string;
          lat: number;
          lng: number;
          sequence: number;
          offset_minutes: number;
          dwell_seconds: number;
        };
        Insert: {
          id?: string;
          route_id: string;
          name: string;
          lat: number;
          lng: number;
          sequence: number;
          offset_minutes?: number;
          dwell_seconds?: number;
        };
        Update: {
          id?: string;
          route_id?: string;
          name?: string;
          lat?: number;
          lng?: number;
          sequence?: number;
          offset_minutes?: number;
          dwell_seconds?: number;
        };
        Relationships: [];
      };
      ticket_messages: {
        Row: {
          id: string;
          ticket_id: string;
          author_id: string | null;
          body: string;
          attachment_path: string | null;
          internal: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          author_id?: string | null;
          body: string;
          attachment_path?: string | null;
          internal?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          author_id?: string | null;
          body?: string;
          attachment_path?: string | null;
          internal?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      tickets: {
        Row: {
          id: string;
          tenant_id: string | null;
          unit: string | null;
          category: Database["public"]["Enums"]["ticket_category"];
          subject: string;
          description: string;
          photo_path: string | null;
          status: Database["public"]["Enums"]["ticket_status"];
          priority: Database["public"]["Enums"]["ticket_priority"];
          source: Database["public"]["Enums"]["ticket_source"];
          device_id: string | null;
          assigned_to: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          unit?: string | null;
          category: Database["public"]["Enums"]["ticket_category"];
          subject: string;
          description?: string;
          photo_path?: string | null;
          status?: Database["public"]["Enums"]["ticket_status"];
          priority?: Database["public"]["Enums"]["ticket_priority"];
          source?: Database["public"]["Enums"]["ticket_source"];
          device_id?: string | null;
          assigned_to?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          unit?: string | null;
          category?: Database["public"]["Enums"]["ticket_category"];
          subject?: string;
          description?: string;
          photo_path?: string | null;
          status?: Database["public"]["Enums"]["ticket_status"];
          priority?: Database["public"]["Enums"]["ticket_priority"];
          source?: Database["public"]["Enums"]["ticket_source"];
          device_id?: string | null;
          assigned_to?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      amenity_busy_periods: { Args: { p_amenity: string; p_from: string; p_to: string }; Returns: { period: string | null; kind: string | null }[] };
      amenity_usage: { Args: { p_from: string; p_to: string }; Returns: { amenity_id: string | null; amenity: string | null; bookings: number | null; hours: number | null; cancelled: number | null; energy_kwh: number | null }[] };
      announcement_recipients: { Args: { a: string }; Returns: string[] };
      announcement_stats: { Args: Record<PropertyKey, never>; Returns: { announcement_id: string | null; audience_size: number | null; read_count: number | null }[] };
      announcement_targets_me: { Args: { a: string }; Returns: boolean };
      bootstrap_admin: { Args: { admin_email: string }; Returns: Database["public"]["Tables"]["profiles"]["Row"] };
      building_tz: { Args: Record<PropertyKey, never>; Returns: string };
      can_operate_run: { Args: { r: string }; Returns: boolean };
      cancel_run: { Args: { p_run: string; p_reason: string }; Returns: Database["public"]["Tables"]["runs"]["Row"] };
      compute_run_metrics: { Args: { p_run: string }; Returns: Database["public"]["Tables"]["shuttle_run_metrics"]["Row"] };
      create_profile_for: { Args: { u: string }; Returns: undefined };
      delay_run: { Args: { p_run: string; p_minutes: number; p_note?: string }; Returns: Database["public"]["Tables"]["runs"]["Row"] };
      deliver_announcement: { Args: { p_id: string }; Returns: number };
      end_run: { Args: { p_run: string }; Returns: Database["public"]["Tables"]["runs"]["Row"] };
      escalate_offline_devices: { Args: { p_after?: string }; Returns: number };
      flag_late_runs: { Args: Record<PropertyKey, never>; Returns: number };
      haversine_km: { Args: { lat1: number; lng1: number; lat2: number; lng2: number }; Returns: number };
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_approved: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_driver: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_staff: { Args: Record<PropertyKey, never>; Returns: boolean };
      laundry_machine_freed: { Args: { p_machine: string }; Returns: number };
      laundry_usage: { Args: { p_from: string; p_to: string }; Returns: { machine_id: string | null; label: string | null; kind: Database["public"]["Enums"]["machine_kind"] | null; cycles: number | null }[] };
      local_time_label: { Args: { ts: string }; Returns: string };
      mark_notifications_read: { Args: { p_ids?: number[] }; Returns: number };
      materialize_runs: { Args: { p_date: string }; Returns: number };
      my_floor: { Args: Record<PropertyKey, never>; Returns: number };
      my_role: { Args: Record<PropertyKey, never>; Returns: Database["public"]["Enums"]["app_role"] };
      my_unit: { Args: Record<PropertyKey, never>; Returns: string };
      next_departures: { Args: { p_limit?: number }; Returns: { run_id: string | null; route_id: string | null; route_name: string | null; departs_at: string | null; status: Database["public"]["Enums"]["run_status"] | null; delay_minutes: number | null; cancel_reason: string | null }[] };
      notify_staff: { Args: { p_title: string; p_body: string; p_url?: string; p_ref?: Json; p_push?: boolean }; Returns: number };
      notify_users: { Args: { p_users: string[]; p_kind: Database["public"]["Enums"]["notification_kind"]; p_title: string; p_body: string; p_url?: string; p_urgent?: boolean; p_push?: boolean; p_email?: boolean; p_ref?: Json }; Returns: number };
      review_tenant: { Args: { target: string; decision: Database["public"]["Enums"]["account_status"]; note?: string }; Returns: Database["public"]["Tables"]["profiles"]["Row"] };
      run_maintenance: { Args: Record<PropertyKey, never>; Returns: Json };
      set_room_override: { Args: { p_room: string; p_mode: Database["public"]["Enums"]["override_mode"]; p_minutes?: number }; Returns: Database["public"]["Tables"]["rooms"]["Row"] };
      set_user_role: { Args: { target: string; new_role: Database["public"]["Enums"]["app_role"] }; Returns: Database["public"]["Tables"]["profiles"]["Row"] };
      shuttle_alert_recipients: { Args: Record<PropertyKey, never>; Returns: string[] };
      staff_ids: { Args: Record<PropertyKey, never>; Returns: string[] };
      start_run: { Args: { p_run: string }; Returns: Database["public"]["Tables"]["runs"]["Row"] };
      start_unscheduled_run: { Args: { p_route: string }; Returns: Database["public"]["Tables"]["runs"]["Row"] };
      ticket_resolution_stats: { Args: { p_from: string; p_to: string }; Returns: { category: Database["public"]["Enums"]["ticket_category"] | null; opened: number | null; resolved: number | null; median_hours: number | null; avg_hours: number | null }[] };
    };
    Enums: {
      account_status: "pending" | "approved" | "rejected" | "suspended";
      announcement_audience: "building" | "floors" | "units";
      announcement_category: "maintenance" | "events" | "safety" | "general";
      app_role: "tenant" | "staff" | "driver" | "admin";
      booking_status: "confirmed" | "cancelled" | "completed" | "no_show";
      command_source: "user" | "rule" | "schedule" | "scheduler" | "failsafe" | "system";
      command_status: "queued" | "sent" | "acked" | "failed" | "expired";
      content_source: "staff" | "system";
      device_event_type: "state_change" | "fault" | "anomaly" | "offline" | "online" | "override";
      device_status: "provisioning" | "online" | "offline" | "fault" | "retired";
      device_type: "ct_node" | "pir" | "relay" | "thermostat" | "ev_charger" | "shuttle_telematics" | "gateway";
      energy_source_kind: "grid" | "battery" | "solar";
      ev_session_status: "requested" | "scheduled" | "charging" | "paused" | "completed" | "cancelled" | "faulted";
      machine_kind: "washer" | "dryer";
      machine_state: "idle" | "running" | "finishing" | "fault" | "offline";
      notification_kind: "shuttle_delay" | "shuttle_cancel" | "shuttle_late" | "announcement" | "ticket_update" | "ticket_new" | "booking_confirmed" | "booking_reminder" | "laundry_free" | "ev_update" | "staff_alert";
      override_mode: "auto" | "force_on" | "force_off";
      run_status: "scheduled" | "active" | "completed" | "cancelled";
      schedule_exception_kind: "no_service" | "cancel_run" | "extra_run" | "retime_run";
      ticket_category: "maintenance" | "noise" | "package" | "lockout" | "amenity" | "shuttle" | "device_fault" | "other";
      ticket_priority: "low" | "normal" | "high" | "urgent";
      ticket_source: "tenant" | "staff" | "system";
      ticket_status: "open" | "in_progress" | "resolved";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
