#!/usr/bin/env node
// Generates web/src/lib/database.types.ts from a Postgres database that has
// the migrations applied, in the shape supabase-js expects. Equivalent to
// `supabase gen types typescript`, without needing Docker.
//
//   node scripts/gen-types.mjs "postgres://postgres@127.0.0.1:54329/postgres" > web/src/lib/database.types.ts
//   (supabase/tests/run.sh --types does this for you)
import { execFileSync } from "node:child_process";

const url = process.argv[2];
if (!url) {
  console.error("usage: gen-types.mjs <postgres url>");
  process.exit(1);
}
const q = (sql) => JSON.parse(execFileSync("psql", ["-X", "-t", "-A", "-d", url, "-c", sql]).toString() || "null") ?? [];

const enums = q(`select coalesce(json_agg(x order by x.name), '[]') from (
  select t.typname as name, json_agg(e.enumlabel order by e.enumsortorder) as labels
  from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' group by t.typname) x`);

const cols = q(`select coalesce(json_agg(x order by x.table_name, x.ordinal_position), '[]') from (
  select c.table_name, c.column_name, c.ordinal_position, c.is_nullable = 'YES' as nullable,
         (c.column_default is not null or c.is_identity = 'YES' or c.is_generated = 'ALWAYS') as has_default,
         c.is_generated = 'ALWAYS' or c.identity_generation = 'ALWAYS' as generated,
         c.udt_name, c.data_type
  from information_schema.columns c join information_schema.tables t
    on t.table_schema = c.table_schema and t.table_name = c.table_name
  where c.table_schema = 'public' and t.table_type = 'BASE TABLE') x`);

// Functions callable over RPC (have named args or none), skipping trigger functions.
const fns = q(`select coalesce(json_agg(x order by x.name), '[]') from (
  select p.proname as name, p.proretset as setof, p.pronargdefaults as ndefaults,
         coalesce(p.proargnames, '{}') as argnames, coalesce(p.proargmodes::text[], '{}') as argmodes,
         (select coalesce(json_agg(format_type(t, null) order by o), '[]')
            from unnest(coalesce(p.proallargtypes, p.proargtypes::oid[])) with ordinality as a(t, o)) as argtypes,
         format_type(p.prorettype, null) as rettype, rt.typtype as rettyptype, rc.relname as retrel
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  join pg_type rt on rt.oid = p.prorettype
  left join pg_class rc on rc.oid = rt.typrelid
  where n.nspname = 'public' and p.prokind = 'f' and p.prorettype <> 'trigger'::regtype
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')) x`);

const enumNames = new Set(enums.map((e) => e.name));
function ts(udt) {
  const arr = udt.startsWith("_");
  const base = arr ? udt.slice(1) : udt;
  let t;
  if (enumNames.has(base)) t = `Database["public"]["Enums"]["${base}"]`;
  else if (["int2", "int4", "int8", "numeric", "float4", "float8", "smallint", "integer", "bigint", "real", "double precision"].includes(base)) t = "number";
  else if (["bool", "boolean"].includes(base)) t = "boolean";
  else if (["json", "jsonb"].includes(base)) t = "Json";
  else t = "string";
  return arr ? `${t}[]` : t;
}
// format_type() names → udt-ish names
function fromFormat(ft) {
  const arr = ft.endsWith("[]");
  let b = ft.replace(/\[\]$/, "").replace(/^public\./, "").replace(/\(.*\)$/, "");
  const map = { "smallint": "int2", "integer": "int4", "bigint": "int8", "boolean": "bool", "double precision": "float8", real: "float4",
    "timestamp with time zone": "timestamptz", "timestamp without time zone": "timestamp", "time without time zone": "time", "character varying": "varchar" };
  b = map[b] ?? b;
  return arr ? `_${b}` : b;
}

const tables = {};
for (const c of cols) (tables[c.table_name] ??= []).push(c);

const out = [];
out.push(`// Generated by scripts/gen-types.mjs from the migrations — do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {`);
for (const [name, cs] of Object.entries(tables)) {
  const row = cs.map((c) => `          ${c.column_name}: ${ts(c.udt_name)}${c.nullable ? " | null" : ""};`).join("\n");
  const ins = cs.filter((c) => !c.generated).map((c) => `          ${c.column_name}${c.nullable || c.has_default ? "?" : ""}: ${ts(c.udt_name)}${c.nullable ? " | null" : ""};`).join("\n");
  const upd = cs.filter((c) => !c.generated).map((c) => `          ${c.column_name}?: ${ts(c.udt_name)}${c.nullable ? " | null" : ""};`).join("\n");
  out.push(`      ${name}: {\n        Row: {\n${row}\n        };\n        Insert: {\n${ins}\n        };\n        Update: {\n${upd}\n        };\n        Relationships: [];\n      };`);
}
out.push(`    };
    Views: { [_ in never]: never };
    Functions: {`);
const seen = new Set();
for (const f of fns) {
  if (seen.has(f.name)) continue; // overloads: keep the first
  seen.add(f.name);
  const modes = f.argmodes.length ? f.argmodes : f.argtypes.map(() => "i");
  const ins = [], outs = [];
  f.argtypes.forEach((t, i) => {
    const m = modes[i];
    const entry = { name: f.argnames[i] || `arg${i}`, type: ts(fromFormat(t)) };
    if (m === "i" || m === "b") ins.push(entry);
    if (m === "o" || m === "t" || m === "b") outs.push(entry);
  });
  const nIn = ins.length;
  const args = ins.map((a, i) => `${a.name}${i >= nIn - f.ndefaults ? "?" : ""}: ${a.type}`).join("; ");
  let ret;
  if (outs.length) ret = `{ ${outs.map((o) => `${o.name}: ${o.type} | null`).join("; ")} }`;
  else if (f.retrel && tables[f.retrel]) ret = `Database["public"]["Tables"]["${f.retrel}"]["Row"]`;
  else if (f.rettype === "void") ret = "undefined";
  else ret = ts(fromFormat(f.rettype));
  if (f.setof) ret = `${ret}[]`;
  out.push(`      ${f.name}: { Args: ${args ? `{ ${args} }` : "Record<PropertyKey, never>"}; Returns: ${ret} };`);
}
out.push(`    };
    Enums: {`);
for (const e of enums) out.push(`      ${e.name}: ${e.labels.map((l) => JSON.stringify(l)).join(" | ")};`);
out.push(`    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
`);
process.stdout.write(out.join("\n"));
